# REFERENCES:
# 1. https://github.com/BrianMitchL/BrianMitchL.github.io/blob/master/_config.yml
# 2. https://github.com/github/government.github.com/blob/gh-pages/_config.yml
# 3. https://github.com/HugoGiraudel/sass-guidelines/blob/master/_config.yml
# 4. https://github.com/plusjade/jekyll-bootstrap/blob/master/_config.yml
# 5. https://help.github.com/en/articles/configuring-jekyll
# 6. https://jekyllrb.com/docs/configuration/default/

#==============================================================================#
# SITE SETTINGS
#==============================================================================#

# Themes are encouraged to use these universal variables, 
# so be sure to set them if your theme uses them.

# SEO
title: djrlj694
description: "A personal website that showcases my software projects and interests"

sub-title: "A software developer's personal website"
author: "Robert Jones"

layout: sidebar
style: dark

#==============================================================================#
# BUILD SETTINGS
#==============================================================================#

# ---------------------------------------------------------------------------- #
# Sass
# ---------------------------------------------------------------------------- #

sass:
  style: :compressed
  # Where you keep your scss files
  #sass_dir: assets/css/
  # Where sass should look for other scss
  #load_paths:
  #  - node_modules/

# ---------------------------------------------------------------------------- #
# Handling Reading
# ---------------------------------------------------------------------------- #

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - vendor

# ---------------------------------------------------------------------------- #
# Filtering Content
# ---------------------------------------------------------------------------- #

# ---------------------------------------------------------------------------- #
# Plugins
# ---------------------------------------------------------------------------- #

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# ---------------------------------------------------------------------------- #
# Conversion
# ---------------------------------------------------------------------------- #

markdown: kramdown

# ---------------------------------------------------------------------------- #
# Serving
# ---------------------------------------------------------------------------- #

# ---------------------------------------------------------------------------- #
# Outputting
# ---------------------------------------------------------------------------- #

# This is the default format. 
# For more, see: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

timezone: America/New_York

# ---------------------------------------------------------------------------- #
# Markdown Processors
# ---------------------------------------------------------------------------- #

# See https://help.github.com/en/articles/configuring-jekyll:
kramdown:
  # Use GitHub Flavored Markdown.
  input: GFM                # Can be overridden.
  auto_ids: true
  syntax_highlighter: rouge # Can't be overridden.
  # Don't replace newlines by <br>s.
  hard_wrap: false          # Can be overridden.
  toc_levels: 1..6

#==============================================================================#
# OTHER/CUSTOM SETTINGS
#==============================================================================#

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    - github-slideshow
    - riverwalk-at-royersford

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: djrlj694
  # hackerrank: your_username
  linkedin: robertljones
  # instagram: your_username
  # keybase: your_username
  # medium: @djrlj694
  medium: "robertljones_56726"
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: djrlj694
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
